/**
 * Pipeline Action Checklist Types
 *
 * Types for the rule-based action checklist system that guides recruiters
 * through pipeline hygiene tasks.
 */

// Action item priorities
export type ActionPriority = 'urgent' | 'important' | 'maintenance';

// Action item categories
export type ActionCategory = 'candidate' | 'job' | 'communication' | 'pipeline';

// Types of actions generated by rules
export type ActionType =
  | 'stuck_candidates'
  | 'unreviewed_apps'
  | 'low_pipeline'
  | 'pending_offer'
  | 'jd_quality'
  | 'stale_job'
  | 'no_interviews'
  | 'hm_feedback'
  | 'status_updates';

// Verification modes for completion checking
export type VerificationMode = 'auto' | 'manual';

/**
 * An individual action item in the checklist
 */
export interface ActionItem {
  id: string;                    // Stable ID: "stuck-stage-{stageId}"
  priority: ActionPriority;
  category: ActionCategory;
  title: string;                 // "Review 5 candidates stuck in Screening"
  description?: string;          // AI-enhanced context (optional)
  completionType: 'action' | 'outcome';
  link?: string;                 // Navigation target when clicked
  metadata: ActionItemMetadata;
}

export interface ActionItemMetadata {
  type: ActionType;
  count?: number;
  jobId?: number;
  stageId?: number;
  daysSince?: number;
  candidateName?: string;
  jobTitle?: string;
  stageName?: string;
  issue?: string;
}

/**
 * Lightweight snapshot for verification - counts only, not full arrays
 */
export interface LightweightSnapshot {
  stuckByStage: Record<number, number>;      // stageId -> count
  unreviewedCount: number;
  pendingOfferCount: number;
  lowPipelineJobIds: number[];               // Just IDs
  staleJobIds: number[];
  shortlistedNoInterviewCount: number;
}

/**
 * A checklist session persisted in localStorage
 */
export interface ChecklistSession {
  id: string;                    // UUID for this session
  userId: number;
  role: string;
  generatedAt: string;           // ISO timestamp
  snapshot: LightweightSnapshot; // Data at generation time
  items: ActionItem[];
  completedIds: string[];        // IDs user has checked
  aiEnhanced: boolean;           // Whether AI layer was applied
  lastVerification?: VerificationResult; // Results from last reanalyze
}

/**
 * Summary of verification for display
 */
export interface VerificationSummary {
  verified: number;
  unverified: number;
  manual: number;
  total: number;
  changes: Array<{
    itemId: string;
    title: string;
    change: string;
    verified: boolean;
    mode: VerificationMode;
  }>;
}

/**
 * Result of verifying completed items
 */
export interface VerificationResult {
  results: Record<string, {
    verified: boolean;
    change: string;
    mode: VerificationMode;
  }>;
  verifiedCount: number;
  totalCount: number;
  manualCount: number;
  readyForAi: boolean;
}

/**
 * Input data for the rule engine
 */
export interface PipelineData {
  // Stuck candidates by stage
  stuckByStage: Record<number, {
    count: number;
    maxDays: number;
    stageName: string;
  }>;

  // Unreviewed applications
  unreviewedCount: number;
  oldestUnreviewedHours: number;

  // Pending offers
  pendingOffers: Array<{
    applicationId: number;
    candidateName: string;
    daysSinceSent: number;
  }>;

  // Shortlisted but no interview
  shortlistedNoInterview: number;

  // Jobs with low pipeline
  jobsWithLowPipeline: Array<{
    jobId: number;
    title: string;
    activeCount: number;
  }>;

  // JD quality issues
  jdIssues: Array<{
    jobId: number;
    title: string;
    issue: string;
  }>;

  // Stale jobs (no activity)
  staleJobs: Array<{
    jobId: number;
    title: string;
    daysSinceActivity: number;
  }>;

  // Candidates awaiting status update
  candidatesNeedingUpdate: number;
}

/**
 * Result of checking if reanalyze is allowed
 */
export interface ReanalyzeCheck {
  allowed: boolean;
  reason: string;
}

/**
 * Grouped action items by priority for rendering
 */
export interface GroupedActionItems {
  urgent: ActionItem[];
  important: ActionItem[];
  maintenance: ActionItem[];
}

// Constants
export const LOW_PIPELINE_THRESHOLD = 3;
export const STUCK_DAYS_URGENT = 7;
export const STUCK_DAYS_IMPORTANT = 3;
export const UNREVIEWED_HOURS_URGENT = 48;
export const OFFER_FOLLOW_UP_DAYS = 3;
export const STALE_JOB_DAYS = 30;
export const SESSION_EXPIRY_HOURS = 24;
export const REANALYZE_COMPLETION_THRESHOLD = 0.7;
